name: Deployment to server

# Github Action to generate a Hugo blog and deploy to webserver

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
   # Steps represent a sequence of tasks that will be executed as part of the job
   build:
    if: github.repository_owner != 'HugoBlox'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch history for Hugo's .GitInfo and .Lastmod
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.WC_HUGO_VERSION }}
          extended: true
      - uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache_runner/
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
        run: |
          echo "Hugo Cache Dir: $(hugo config | grep cachedir)"
          hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public
      - name: upload
        uses: bxb100/action-upload-webdav@main
        with:
            webdav_address: https://gea.ing.unrc.edu.ar
            webdav_username: ${{secrets.username}}
            webdav_password: ${{secrets.password}}
            webdav_upload_path: "/nextcloud/remote.php/dav/files/faguilera/faguilera"
            files: "./public/**"
            keep_structure: true



#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
        # Copy build folder to remote using rsync
 #       - uses: actions/checkout@v3
  #      - name: upload
   #       uses: bxb100/action-upload-webdav@main
    #      with:
     #       webdav_address: ${{secrets.address}}
          #  webdav_username: ${{secrets.username}}
         #   webdav_password: ${{secrets.password}}
        #    webdav_upload_path: "/nextcloud/remote.php/dav/files/faguilera"
       #     files: "./public/**"
      #      keep_structure: true
      
     # - name: Rsync Deployments Action
     #   uses: Burnett01/rsync-deployments@5.2
     #   with:
     #     switches: -avzr --delete
     #     path: public/
     #     remote_path: /home/user/html/
     #     remote_host: remote.host
     #     remote_user: user
     #     remote_key: $
